[placement]
mode = "smart"

[env.staging]
kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "VAR_KV_NAMESPACE_STG_ID" }
]

[env.production]
kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "VAR_KV_NAMESPACE_ID" }
]
